apiVersion: v1
kind: Service
metadata:
  name: matches-service   # Name service
  labels:
    app: matches         # Optional label
spec:
  type: NodePort         # Makes the app accessible on a specific port
  selector:
    app: matches         # Must match the label in deployment.yaml
  ports:
    - protocol: TCP
      port: 80           # Port the service listens on (internal)
      targetPort: 80      # Port app runs on (must match containerPort)
      nodePort: 30080     # Port accessible on machine (30000-32767)