apiVersion: apps/v1
kind: Deployment
metadata:
  name: matches-deployment   # Name deployment
spec:
  selector:
    matchLabels:
      app: matches           # Must match the label below
  replicas: 1               # Only 1 replica (copy) of app
  template:
    metadata:
      labels:
        app: matches        # Label for app
    spec:
      containers: 
        - name: matches     # Name of the container
          image: mariakalafati/devops:1.0  # Docker Hub image
          imagePullPolicy: Always
          ports:
            - containerPort: 80  # Port your app runs inside the container
  